### PR TITLE
Skill and icon fixes

### PR DESCRIPTION
**Pull request by DanDuhon**
Fixed some upside down skill icons in Monk.
Fixed Monk background file name so it shows now.
Fixed file name of the Master of Ice icon so it loads now.
Fixed skill text and icon for Poison Cloud.

Also ran "npm audit fix".  Things still seem to work but I don't know enough react or js to do anything else.  I honestly don't know what the changes to package-lock.json, package.json, and yarn.lock do, but I bumped the version number up to 1.1.5 because why not.

### CODE REVIEW

**Comment by ianlamb** [comment]
Awesome, thanks for fixing this stuff! 🎉

You didn't make any changes to `skills.json` did you? I'm guessing the diff is just because of formatting, but I wanted to check because that is just a generated file. The source of truth is actually a spreadsheet outside of this project, so it would overwrite the json.

**Comment by ianlamb** [comment]
This has been deployed, thanks again!

**Comment by DanDuhon** [comment]
Sure, no problem!

Ah I did actually edit skills.json. The only one that was changed in there was Poison Cloud since it differs quite a bit from what's in game at the moment.

**Comment by ianlamb** [comment]
Got it, I will update the spreadsheet with that so it doesn't get lost.

**Pull request merged**
